dist: xenial
services:
  - xvfb  # adds X server for nightwatch/selenium/chromedriver
language: node_js
node_js:
  - 11.12 # need this version for Jest 24, prior versions have SYMBOL bugs

install:
  - yarn install

script:
  - yarn run lint
  - yarn run test:unit
  - yarn run test:e2e
  - yarn run build
  - echo "config.qmk.fm" > dist/CNAME

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: dist
  github_token: $GH_TOKEN
  keep_history: false
  on:
    branch: master

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/428080202c6aa8650101
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
