addons:
  apt:
    packages:
      # Ubuntu 16+ does not install this dependency by default, so we need to install it ourselves
      - libgconf-2-4
language: node_js
node_js:
  - 11.12 # need this version for Jest 24, prior versions have SYMBOL bugs

cache:
  # Caches $HOME/.npm when npm ci is default script command
  # Caches node_modules in all other cases
  npm: true
  directories:
    # we also need to cache folder with Cypress binary
    - ~/.cache

install:
  - yarn install
  - npx cypress install

script:
  - yarn run prettier:check
  - yarn run prettier:json:check
  - yarn run lint
  - yarn run test:unit
  - yarn run test:cypress:ci
  # Echo the travis commit to env file to be set in the build process
  - echo VUE_APP_TRAVIS_COMMIT=$TRAVIS_COMMIT >> .env.production
  - yarn run build

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: dist
  github_token: $GH_TOKEN
  keep_history: false
  fqdn: config.qmk.fm
  on:
    branch: master

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/428080202c6aa8650101
    on_success: always # options: [always|never|change] default: always
    on_failure: always # options: [always|never|change] default: always
    on_start: never # options: [always|never|change] default: always
